name: "Build Core image"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test query
      id: runtime
      run: |
        TAGS=${GITHUB_REF}
        echo ::set-output name=tags::${TAGS}
